### ISSUE TITLE
Peggle (SE 240x320 versions) missing graphics

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#66]
In Peggle, starting with the 3rd level, there are green pegs that can be hit with the ball. These are invisible on the current build, while they can be hit, the game is harder to play because of that. On the screenshot, I aimed the ball at an invisible green peg.

![Image](https://github.com/user-attachments/assets/32c33a11-ed44-4499-bd2c-0ccf24b34445)

One weirder issue is that (especially in the main menu) the game can either duplicate inputs with the same or a different input, or even generate a phantom input out of nowhere. I don't have this issue elsewhere, so I don't think it's my keyboard.

Some Nokia S60 versions of the game do the weird thing where the music and sounds are all in a single midi file, and the game uses timestamps to jump around the midi file to play music and sounds, but I haven't yet gotten to trying out those kinds of versions on freej2me-plus.

I will attach a save file for the 3rd level.

[Peggle_save.zip](https://github.com/user-attachments/files/19071512/Peggle_save.zip)

**Comment by TwoSpacesSG** [comment]
The phantom inputs issue also affects Castlevania: Order of Shadows.

**Comment by TwoSpacesSG** [comment]
There is also something weird with inputs in The Legend of Spyro: A New Beginning (SE 240x320). It seems like the game barely responds to the left and right inputs on the "enable sound and vibration" screen, and the confirm softkey on this screen doesn't seem to work at all (meaning compatibility with this game is now broken).

**Comment by AShiningRay** [comment]
Input issues should have been resolved by 81ffbce170e94f52c1a89c8535934a49f435a1af

**Comment by TwoSpacesSG** [comment]
I've not tested Castlevania yet but in Peggle the inputs are indeed fixed. The graphical issue remains.

Regarding Spyro, I'm stupid and had the wrong keycodes selected, and also the sound and vibration screen writes to RMS every time you change the selection. However, it is true that in The Legend of Spyro games, some inputs are disregarded in FreeJ2ME+, something that doesn't happen on S60 or KEmnnmod. It's most obvious when mashing directional keys in the main menu. I think it's best to proceed with this issue to have it about the graphics in Peggle, and I will create a separate report about Legend of Spyro game inputs.

**Comment by TwoSpacesSG** [comment]
The graphics in this game have regressed:

![Image](https://github.com/user-attachments/assets/0f961872-1e89-464e-afe4-5bf0dce24e39)
![Image](https://github.com/user-attachments/assets/b743714b-b00c-4b40-8013-28a7bbeda625)

**Comment by AShiningRay** [comment]
> The graphics in this game have regressed:

Seems to be an issue of the jar not clearing the draw area before redrawing. I wonder what it's doing behind the scenes to cause this kind of issue...

Won't have time for that anytime soon though (that's why i focused on those large pushes the last few days).

**Comment by TwoSpacesSG** [comment]
> The graphics in this game have regressed

This is now fixed, but the issue with the invisible bonus pegs remains. Also it looks like this game uses System.gc for timing from the looks of it as well, but it still runs too fast, so it's better to limit it to 30 fps.

**Comment by TwoSpacesSG** [comment]
Forgot to mention, it's now "improved" in that it renders one green peg on-screen as opposed to all two that should be on-screen at a given time (and that's in the third level, then the game introduces purple pegs, of which there's 1 at a time).

![Image](https://github.com/user-attachments/assets/ee8f1d0f-aa64-46c7-9b24-54a589a677b0)

**Comment by AShiningRay** [comment]
After some internal testing, we found out that this game is either hitting a corner case in the MIDP drawRGB method that SE's VM accounts for and the standard implementation (and thus Nokia) are not, or SE and Nokia differ in some way in how they implemented their drawRGB calls.

Whichever's the case, the issue boils down to: Nokia and reference MIDP expect the drawRGB x and y coordinates to be translated by the graphics context's current translation, while SE apparently doesn't... this reflects in actual hardware, as SE phones show no bonus pegs when running Nokia versions.

This is a fundamental difference in how the data is interpreted and thrown to the screen so the only "fix" i can think of is a compatibility flag. Coming soon...

**Comment by TwoSpacesSG** [comment]
For some reason the drawRGB flag was discarded in commit 202203ebc04346fceff89f5dc22f27fdebc63a2d . Now various versions of Peggle are not playable.

**Comment by AShiningRay** [comment]
Closing this again.
