### ISSUE TITLE
Baldur's Gate: Button not working?

### ISSUE THREAD

**Issue by Magstic** [TASEmulators/freej2me-plus#80]
**Issue**

These Issue are abstract, they are not intuitive…
This game has many bugs, but it can be completed.(Use N86)

- When opening the backpack and viewing item details, the return key (right soft key) is ineffective.

- Press the `*` key and you can't use the navigation keys to view the map.

- Sometimes the return button will become ineffective when you open the game introduction or game about, but the probability is very low.

- When you re-enter the game, the button texts at the bottom left and right corners of the screen may display incorrectly.

- There may be other mistakes, but the above ones made it impossible for me to advance the plot.

Game: http://dedomil.net/games/3138/screen/8

**Comment by TwoSpacesSG** [comment]
For research and investigation's sake, I re-uploaded the 21 versions of this game that I know of, here: (edit: link removed now that this is resolved)

**Comment by AShiningRay** [comment]
Should be fixed now. Game hits a MIDP corner case where the command handling is left entirely up to the implementation (duplicates should not be treated as an error, but the implementation has to decide what to really do with it). So FreeJ2ME just ignores those duplicated calls now.

**Comment by Magstic** [comment]
The back button now works fine, but when viewing a map (pressing the * key), you still cannot use the navigation keys to scroll the screen.

This does not affect the game's completion.
I'm going to try to Complete this game to try to figure out what other possible issues there are.(Hopefully not :D)


Edit ADD: Oh sorry, I think I overlooked a problem. The menu covers the character's attribute bar www

![Image](https://github.com/user-attachments/assets/e8d7bb6f-e10f-404a-8ed4-07c701ee407c)

**Comment by AShiningRay** [comment]
About the minimap movement after pressing *... i seem to be able to do it fine on my end. It's not the smoothest thing ever, but even normal movement in this game feels jank (even in KEmulator).

Edit: This menu stuff is also an easy fix, if it's caused by what i think it is.

**Comment by AShiningRay** [comment]
Oh now that i tested it a bit more, in some situations the minimap doesn't move at all (looks like it can move fine if i explore the map a bit before trying to use it)... but it's also like this in KEmulator. In fact, it seems to behave the exact same way in both, which is really strange and points to some sort of game bug more than anything.


Edit: Also confirmed the same behavior in J2ME-Loader, so it's definitely something in the game. Either it does something that only the target device supports (and is out of MIDP-Spec), or it's just buggy.

**Comment by Magstic** [comment]
Well, I think this is a bug in the game itself, I'm very sorry...
Next I will try to complete the game.

**Comment by AShiningRay** [comment]
> Well, I think this is a bug in the game itself, I'm very sorry... Next I will try to complete the game.

That's fine, Sorrent games are often very janky and have questionable development and design decisions (as can be noticed by it sending the same command to be added multiple times for example). This minimap issue could very well be a side-effect of their design philosophy.

**Comment by Magstic** [comment]
There is no problem with the game, you can complete it normally!
